const data = {
    products:[{
        _id:'1',
        name:'book',
        category:'pages',
        image:'/Images/p1.jpg',
        price:10,
        brand:'brand',
        rating:1,
        numReviews: 15,
        description:'high quality product',
        countInStock : 2,
    },{
        _id:'2',
        name:'book2',
        category:'pages2',
        image:'../Images/p3.jpg',
        price:1200,
        brand:'brand2',
        rating:5,
        numReviews: 154,
        description:'high quality product',
        countInStock : 21,
    },{
        _id:'3',
        name:'book3',
        category:'pages3',
        image:'../Images/p2.jpg',
        price:12,
        brand:'brand3',
        rating:1.5,
        numReviews: 105,
        description:'high quality product',
        countInStock : 12,
    },{
        _id:'4',
        name:'book4',
        category:'pages4',
        image:'../Images/p3.jpg',
        price:130,
        brand:'brand',
        rating:4.5,
        numReviews: 16,
        description:'high quality product',
        countInStock : 5,
    },{
        _id:'5',
        name:'book5',
        category:'pages5',
        image:'../Images/p2.jpg',
        price:120,
        brand:'brand5',
        rating:3.5,
        numReviews: 8,
        description:'high quality product',
        countInStock : 12,
    },{
        _id:'6',
        name:'book6',
        category:'pages6',
        image:'../Images/p1.jpg',
        price:100,
        brand:'brand6',
        rating:4.5,
        numReviews: 18,
        description:'high quality product',
        countInStock : 9,
    },{
        _id:'7',
        name:'book7',
        category:'pages7',
        image:'../Images/p1.jpg',
        price:10,
        brand:'brand7',
        rating:2.5,
        numReviews: 15,
        description:'high quality product',
        countInStock : 7,
    },{
        _id:'8',
        name:'book8',
        category:'pages8',
        image:'../Images/p2.jpg',
        price:120,
        brand:'brand8',
        rating:2,
        numReviews: 1,
        description:'high quality product',
        countInStock : 0,
    },{
        _id:'9',
        name:'book9',
        category:'pages9',
        image:'../Images/p3.jpg',
        price:120,
        brand:'brand',
        rating:3,
        numReviews: 12,
        description:'high quality product',
        countInStock : 3,
    },

    ]};

    export default data;